Fake content for oai provider
moravianlibrary/kramerius pull request #214
Opened 2017-10-10 12:49 UTC by xermak00

2017-10-11 07:02 UTC, MartinRumanek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +    private void sendFakeContent(HttpServletResponse resp) {
přejmenoval bych na sendErrorMessage

2017-10-11 07:05 UTC, MartinRumanek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +    private void sendFakeContent(HttpServletResponse resp) {
Nedával bych tam code="404", protože ty chyby se můžou lišit....lepší bude mít atribut message a před tam message z IOException. Pokud IOEXception nenese rozumnou hlášku bude pravděpodobně nutné upravit DrKrameriusV4Writer.

2017-10-11 07:13 UTC, MartinRumanek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +        try {
Zavírat zdroje by se mělo vždy v bloku finally, nebo nejlépe v tomto případě použít try-with-resources (už můžeme konečně používat konstruky z novější Javy - v IDE si to přepni rovnou na Javu 8)

2017-10-11 07:18 UTC, MartinRumanek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +            resp.getWriter().close();
Close - zavírat zdroje bys měl vždy v bloku finally. Kramerius už konečně opustil JDK 6, takže můžeme používat novější konstrukty. Např. try-with-resources, PrintWriter implementuje rozhraní closeable, takže by to mělo jít.

2017-10-11 07:21 UTC, MartinRumanek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +        String emptyXml = "<error code=\"404\">";
Neposílat 404, ale spíše getMessage z IOException. Pokud neobsahuje dobrou message bude nutné upravit DrKrameriusV4Writer.java

2017-10-11 07:25 UTC, leiblix requested changes
Jo, to by mohlo fungovat. Testoval jsi to? Nebo to zkusíme rovnou na produkci?

Před začleněním do codebase budu chtít vyřešit pár drobností, které jsem napsal do komentářů.

2017-10-11 07:44 UTC, jkremlacek requested changes

2017-10-11 07:44 UTC, jkremlacek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +   @Override
Chyba odsazení.

2017-10-11 07:44 UTC, jkremlacek commented on search/src/java/cz/incad/Kramerius/oai/OaiServlet.java
> +        String emptyXml = "<error code=\"404\">";
Proměnnou bych potom přejmenoval na `xmlContent`, emptyXml by mohlo evokovat, že se jedná o prázdný řetězec.

2017-10-18 10:36 UTC, MartinRumanek commented
Prosím teda prosím otestovat na produkci...s nasazením ti může pomoci @dsecik .

2017-10-18 11:04 UTC, jkremlacek approved these changes

2017-10-25 08:42 UTC, MartinRumanek commented
Hezké 👍 

Prosím udělej squash přes ty tři commity git rebase -i HEAD~3 (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

A commit message přepiš na:

Issue #565: fix oai export (missing Fedora object)

_______
Pak už to zamerguju do upstreamu. Díky!

2017-10-26 05:46 UTC, closed without merging